apiVersion: v1
kind: Service
metadata:
  name: demo-course
  namespace: demo-aks-course
spec:
  type: LoadBalancer
  selector:
    app: demo-course
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000